#' Download example data
#'
#' `load_exdata` downloads and saves example data as temporary files. The list of directories returned contains the files in order:
#'  \describe{
#'     \item{8_trunc.npz}{Numpy sparse matrix generated by python package `methSCAn` with dimensions 129300644x833. Contains CpG methylation of chromosome 8 from a murine adult NSC lineage. Information was reduced to the genomic region 8628100-8684100.}
#'     \item{8_GpC_trunc.npz}{Numpy sparse matrix generated by python package `methSCAn` with dimensions 1129301117x797. Contains GpC methylation of chromosome 8 from a murine adult NSC lineage. Information was reduced to the genomic region 8628100-8684100.}
#'     \item{cell-annotation.tsv}{Tsv file containing cell IDs and pseudotimes of the cells used for the scNMT-sequencing to receive the original Numpy sparse matrices.}
#' }
#'
#' @return List of directories, in which the temporary files are saved.
#' @export
#'
#' @source Original files received from \href{https://doi.org/10.1038/s41586-024-07898-9}{(Kremer, Cerrizuela, et al., 2024)}. The sparse matrices were simplified by removing the values outside the chosen region.
#'
#' @references Kremer, L. P. M., Cerrizuela, S., El-Sammak, H., Al Shukairi, M. E., Ellinger, T., Straub, J., Korkmaz, A., Volk, K., Brunken, J., Kleber, S., Anders, S., & Martin-Villalba, A. (2024). DNA methylation controls stemness of astrocytes in health and ischaemia. Nature, 634(8033), 415-423. https://doi.org/10.1038/s41586-024-07898-9
#'
#'
#' @examples load_exdata()
load_exdata <- function() {

  url <- "https://heibox.uni-heidelberg.de/f/5f14053387914445b89f/?dl=1"
  tempfile <- file.path(tempdir(), "8_trunc.npz")
  download.file(url, tempfile, mode = "wb")


  url2 <- "https://heibox.uni-heidelberg.de/f/b76f7887a3f746b98e84/?dl=1"
  tempfile2 <- file.path(tempdir(), "8_GpC_trunc.npz")
  download.file(url2, tempfile2, mode = "wb")

  url3 <- "https://heibox.uni-heidelberg.de/f/d6b63b2211e14b2a88f2/?dl=1"
  tempfile3 <- file.path(tempdir(), "cell-annotation.tsv")
  download.file(url3, tempfile3, mode = "wb")

  # Return the loaded data
  return(list(tempfile, tempfile2, tempfile3))
}
